import type { CanvasBlockDefinition } from '../types'

export const CANVAS_BLOCKS: CanvasBlockDefinition[] = [
  // ── Hero ──────────────────────────────────────────────────────────────────
  {
    id: 'canvas-hero',
    name: 'Hero',
    description: 'Full-width hero with headline, subtext, and CTA',
    icon: 'i-lucide-layout-template',
    category: 'content',
    component: 'CanvasBlockHero',
    thumbnailColor: '#eef2ff',
    fields: [
      { key: 'headline', label: 'Headline', type: 'text', placeholder: 'Your big headline' },
      { key: 'subtext', label: 'Subtext', type: 'textarea', placeholder: 'Supporting text…' },
      { key: 'ctaLabel', label: 'Primary button label', type: 'text', placeholder: 'Get started' },
      { key: 'ctaUrl', label: 'Primary button URL', type: 'url', placeholder: '/contact' },
      { key: 'ctaBgColor', label: 'Primary button colour', type: 'color' },
      { key: 'cta2Label', label: 'Secondary button label', type: 'text', placeholder: 'Learn more' },
      { key: 'cta2Url', label: 'Secondary button URL', type: 'url', placeholder: 'https://github.com/...' },
      {
        key: 'align',
        label: 'Alignment',
        type: 'select',
        options: [
          { label: 'Left', value: 'left' },
          { label: 'Center', value: 'center' },
          { label: 'Right', value: 'right' },
        ],
      },
      { key: 'logoIcon', label: 'Logo icon class (optional)', type: 'text', placeholder: 'i-lucide-layers' },
      { key: 'showDecorations', label: 'Show glow & grid overlay', type: 'toggle' },
      { key: 'bgGradient', label: 'Background gradient (CSS)', type: 'text', placeholder: 'linear-gradient(to bottom right, #030712, #111827, #030712)' },
      { key: 'bgColor', label: 'Background colour (fallback)', type: 'color' },
      { key: 'textColor', label: 'Text colour', type: 'color' },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      headline: 'Welcome to our site',
      subtext: 'We help you build amazing things.',
      ctaLabel: 'Get started',
      ctaUrl: '/',
      align: 'center',
      bgColor: '#ffffff',
      textColor: '#111827',
      padding: { top: 80, right: 24, bottom: 80, left: 24, unit: 'px' },
    },
  },

  // ── Rich text ─────────────────────────────────────────────────────────────
  {
    id: 'canvas-text',
    name: 'Text',
    description: 'Rich text content block',
    icon: 'i-lucide-type',
    category: 'content',
    component: 'CanvasBlockText',
    thumbnailColor: '#f9fafb',
    fields: [
      { key: 'content', label: 'Content', type: 'richtext' },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      content: '<p>Start writing your content here.</p>',
      padding: { top: 24, right: 24, bottom: 24, left: 24, unit: 'px' },
    },
  },

  // ── Image ─────────────────────────────────────────────────────────────────
  {
    id: 'canvas-image',
    name: 'Image',
    description: 'Single image with optional caption',
    icon: 'i-lucide-image',
    category: 'media',
    component: 'CanvasBlockImage',
    thumbnailColor: '#f3f4f6',
    fields: [
      { key: 'src', label: 'Image URL', type: 'image' },
      { key: 'alt', label: 'Alt text', type: 'text', placeholder: 'Describe the image' },
      { key: 'caption', label: 'Caption', type: 'text', placeholder: 'Optional caption' },
      {
        key: 'width',
        label: 'Width',
        type: 'select',
        options: [
          { label: 'Full width', value: 'full' },
          { label: 'Large (75%)', value: 'lg' },
          { label: 'Medium (50%)', value: 'md' },
          { label: 'Small (33%)', value: 'sm' },
        ],
      },
      {
        key: 'align',
        label: 'Alignment',
        type: 'select',
        options: [
          { label: 'Left', value: 'left' },
          { label: 'Center', value: 'center' },
          { label: 'Right', value: 'right' },
        ],
      },
      { key: 'rounded', label: 'Rounded corners', type: 'toggle' },
      { key: 'focalX', label: 'Focal point X (%)', type: 'number', min: 0, max: 100 },
      { key: 'focalY', label: 'Focal point Y (%)', type: 'number', min: 0, max: 100 },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      src: '',
      alt: '',
      caption: '',
      focalX: 50,
      focalY: 50,
      width: 'full',
      align: 'center',
      rounded: false,
      padding: { top: 16, right: 24, bottom: 16, left: 24, unit: 'px' },
    },
  },

  // ── Video ─────────────────────────────────────────────────────────────────
  {
    id: 'canvas-video',
    name: 'Video',
    description: 'YouTube, Vimeo, or Cloudflare Stream video',
    icon: 'i-lucide-play-circle',
    category: 'media',
    component: 'CanvasBlockVideo',
    thumbnailColor: '#1e1e2e',
    fields: [
      { key: 'url', label: 'Video URL', type: 'url', placeholder: 'YouTube, Vimeo, or Cloudflare Stream URL...' },
      {
        key: 'aspectRatio',
        label: 'Aspect ratio',
        type: 'select',
        options: [
          { label: '16:9 (widescreen)', value: '16:9' },
          { label: '4:3 (classic)', value: '4:3' },
          { label: '1:1 (square)', value: '1:1' },
          { label: '9:16 (portrait)', value: '9:16' },
        ],
      },
      { key: 'caption', label: 'Caption', type: 'text', placeholder: 'Optional caption…' },
      { key: 'autoplay', label: 'Autoplay', type: 'toggle' },
      { key: 'muted', label: 'Muted', type: 'toggle', condition: p => Boolean(p.autoplay) },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      url: '',
      aspectRatio: '16:9',
      caption: '',
      autoplay: false,
      muted: false,
      padding: { top: 16, right: 24, bottom: 16, left: 24, unit: 'px' },
    },
  },

  // ── Columns ───────────────────────────────────────────────────────────────
  {
    id: 'canvas-columns',
    name: 'Columns',
    description: 'Multi-column layout with rich text',
    icon: 'i-lucide-columns-3',
    category: 'layout',
    component: 'CanvasBlockColumns',
    thumbnailColor: '#eff6ff',
    fields: [
      {
        key: 'columns',
        label: 'Number of columns',
        type: 'select',
        options: [
          { label: '2 columns', value: '2' },
          { label: '3 columns', value: '3' },
          { label: '4 columns', value: '4' },
        ],
      },
      { key: 'col1', label: 'Column 1', type: 'richtext' },
      { key: 'col2', label: 'Column 2', type: 'richtext' },
      { key: 'col3', label: 'Column 3', type: 'richtext', condition: p => ['3', '4'].includes(p.columns as string) },
      { key: 'col4', label: 'Column 4', type: 'richtext', condition: p => p.columns === '4' },
      { key: 'gap', label: 'Gap (px)', type: 'number', min: 0, max: 64, step: 4 },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      columns: '2',
      col1: '<p>Column one content.</p>',
      col2: '<p>Column two content.</p>',
      col3: '<p>Column three content.</p>',
      col4: '<p>Column four content.</p>',
      gap: 24,
      padding: { top: 24, right: 24, bottom: 24, left: 24, unit: 'px' },
    },
  },

  // ── Features grid ─────────────────────────────────────────────────────────
  {
    id: 'canvas-features',
    name: 'Features',
    description: 'Grid of icon + title + description cards',
    icon: 'i-lucide-layout-grid',
    category: 'content',
    component: 'CanvasBlockFeatures',
    thumbnailColor: '#fafaff',
    fields: [
      { key: 'sectionLabel', label: 'Section label (e.g. "Everything you need")', type: 'text', placeholder: 'Everything you need' },
      { key: 'sectionTitle', label: 'Section title', type: 'text', placeholder: 'Built for real projects' },
      { key: 'sectionDesc', label: 'Section description', type: 'textarea' },
      {
        key: 'numFeatures',
        label: 'Number of features',
        type: 'select',
        options: [
          { label: '1', value: 1 as unknown as string },
          { label: '2', value: 2 as unknown as string },
          { label: '3', value: 3 as unknown as string },
          { label: '4', value: 4 as unknown as string },
        ],
      },
      {
        key: 'style',
        label: 'Card style',
        type: 'select',
        options: [
          { label: 'Plain', value: 'plain' },
          { label: 'Card (bordered)', value: 'card' },
          { label: 'Icon on top', value: 'icon-top' },
        ],
      },
      {
        key: 'align',
        label: 'Alignment',
        type: 'select',
        options: [
          { label: 'Center', value: 'center' },
          { label: 'Left', value: 'left' },
        ],
      },
      { key: 'iconColor', label: 'Icon colour', type: 'color' },
      { key: 'bgColor', label: 'Background colour', type: 'color' },
      // Feature 1
      { key: 'feat1Icon', label: 'Feature 1 — Icon class', type: 'text', placeholder: 'i-lucide-zap' },
      { key: 'feat1Title', label: 'Feature 1 — Title', type: 'text', placeholder: 'Fast & reliable' },
      { key: 'feat1Desc', label: 'Feature 1 — Description', type: 'textarea' },
      // Feature 2
      { key: 'feat2Icon', label: 'Feature 2 — Icon class', type: 'text', placeholder: 'i-lucide-shield-check', condition: p => Number(p.numFeatures) >= 2 },
      { key: 'feat2Title', label: 'Feature 2 — Title', type: 'text', condition: p => Number(p.numFeatures) >= 2 },
      { key: 'feat2Desc', label: 'Feature 2 — Description', type: 'textarea', condition: p => Number(p.numFeatures) >= 2 },
      // Feature 3
      { key: 'feat3Icon', label: 'Feature 3 — Icon class', type: 'text', placeholder: 'i-lucide-sparkles', condition: p => Number(p.numFeatures) >= 3 },
      { key: 'feat3Title', label: 'Feature 3 — Title', type: 'text', condition: p => Number(p.numFeatures) >= 3 },
      { key: 'feat3Desc', label: 'Feature 3 — Description', type: 'textarea', condition: p => Number(p.numFeatures) >= 3 },
      // Feature 4
      { key: 'feat4Icon', label: 'Feature 4 — Icon class', type: 'text', placeholder: 'i-lucide-globe', condition: p => Number(p.numFeatures) >= 4 },
      { key: 'feat4Title', label: 'Feature 4 — Title', type: 'text', condition: p => Number(p.numFeatures) >= 4 },
      { key: 'feat4Desc', label: 'Feature 4 — Description', type: 'textarea', condition: p => Number(p.numFeatures) >= 4 },
      { key: 'gap', label: 'Gap (px)', type: 'number', min: 8, max: 96, step: 8 },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      numFeatures: 3,
      style: 'plain',
      align: 'center',
      iconColor: '#6366f1',
      bgColor: '#ffffff',
      feat1Icon: 'i-lucide-zap',
      feat1Title: 'Fast & reliable',
      feat1Desc: 'Built for performance from the ground up.',
      feat2Icon: 'i-lucide-shield-check',
      feat2Title: 'Secure by default',
      feat2Desc: 'Enterprise-grade security you can trust.',
      feat3Icon: 'i-lucide-sparkles',
      feat3Title: 'Easy to use',
      feat3Desc: 'Intuitive interface your whole team will love.',
      feat4Icon: 'i-lucide-globe',
      feat4Title: 'Works everywhere',
      feat4Desc: 'Access from any device, any time.',
      gap: 32,
      padding: { top: 48, right: 24, bottom: 48, left: 24, unit: 'px' },
    },
  },

  // ── Testimonial ───────────────────────────────────────────────────────────
  {
    id: 'canvas-testimonial',
    name: 'Testimonial',
    description: 'Customer quote with author, role, and star rating',
    icon: 'i-lucide-quote',
    category: 'content',
    component: 'CanvasBlockTestimonial',
    thumbnailColor: '#fefce8',
    fields: [
      { key: 'quote', label: 'Quote', type: 'textarea', placeholder: 'What did they say?' },
      { key: 'author', label: 'Author name', type: 'text', placeholder: 'Jane Smith' },
      { key: 'role', label: 'Role / title', type: 'text', placeholder: 'CEO' },
      { key: 'company', label: 'Company', type: 'text', placeholder: 'Acme Inc.' },
      { key: 'avatar', label: 'Avatar URL', type: 'image' },
      { key: 'rating', label: 'Star rating (0 = hide)', type: 'number', min: 0, max: 5, step: 1 },
      {
        key: 'style',
        label: 'Style',
        type: 'select',
        options: [
          { label: 'Card (bordered)', value: 'card' },
          { label: 'Simple', value: 'simple' },
          { label: 'Large quote', value: 'large' },
        ],
      },
      {
        key: 'align',
        label: 'Alignment',
        type: 'select',
        options: [
          { label: 'Center', value: 'center' },
          { label: 'Left', value: 'left' },
        ],
      },
      { key: 'bgColor', label: 'Background colour', type: 'color' },
      { key: 'textColor', label: 'Text colour', type: 'color' },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      quote: 'This product completely changed how our team works.',
      author: 'Jane Smith',
      role: 'Product Manager',
      company: 'Acme Inc.',
      avatar: '',
      rating: 5,
      style: 'card',
      align: 'center',
      bgColor: '#ffffff',
      textColor: '#111827',
      padding: { top: 48, right: 24, bottom: 48, left: 24, unit: 'px' },
    },
  },

  // ── CTA Banner ────────────────────────────────────────────────────────────
  {
    id: 'canvas-cta',
    name: 'CTA Banner',
    description: 'Call-to-action strip with heading and button',
    icon: 'i-lucide-megaphone',
    category: 'cta',
    component: 'CanvasBlockCta',
    thumbnailColor: '#ecfdf5',
    fields: [
      { key: 'headline', label: 'Headline', type: 'text', placeholder: 'Ready to get started?' },
      { key: 'subtext', label: 'Subtext', type: 'text', placeholder: 'Join thousands of happy customers.' },
      { key: 'btnLabel', label: 'Button label', type: 'text', placeholder: 'Sign up free' },
      { key: 'btnUrl', label: 'Button URL', type: 'url', placeholder: '/signup' },
      { key: 'bgColor', label: 'Background colour', type: 'color' },
      { key: 'textColor', label: 'Text colour', type: 'color' },
      { key: 'btnColor', label: 'Button colour', type: 'color' },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      headline: 'Ready to get started?',
      subtext: 'Join thousands of happy customers.',
      btnLabel: 'Sign up free',
      btnUrl: '/signup',
      bgColor: '#00dc82',
      textColor: '#0f172a',
      btnColor: '#0f172a',
      padding: { top: 48, right: 24, bottom: 48, left: 24, unit: 'px' },
    },
  },

  // ── Spacer ────────────────────────────────────────────────────────────────
  {
    id: 'canvas-spacer',
    name: 'Spacer',
    description: 'Empty vertical space between blocks',
    icon: 'i-lucide-move-vertical',
    category: 'layout',
    component: 'CanvasBlockSpacer',
    thumbnailColor: '#f9fafb',
    fields: [
      { key: 'height', label: 'Height (px)', type: 'number', min: 8, max: 400, step: 8 },
      { key: 'showLine', label: 'Show divider line', type: 'toggle' },
    ],
    defaultProps: {
      height: 48,
      showLine: false,
    },
  },

  // ── GDPR Cookie Banner ────────────────────────────────────────────────────
  {
    id: 'canvas-gdpr',
    name: 'GDPR Banner',
    description: 'Sticky cookie consent banner at the bottom of the screen',
    icon: 'i-lucide-cookie',
    category: 'cta',
    component: 'CanvasBlockGdpr',
    thumbnailColor: '#fff1f2',
    fields: [
      { key: 'text', label: 'Consent text', type: 'textarea' },
      { key: 'acceptLabel', label: 'Accept button label', type: 'text' },
      { key: 'declineLabel', label: 'Decline button label (optional)', type: 'text' },
      {
        key: 'targeting',
        label: 'Geolocation targeting',
        type: 'select',
        options: [
          { label: 'Show to everyone', value: 'everyone' },
          { label: 'Only show in EU/EEA/UK (GDPR Zone)', value: 'gdpr-only' },
        ],
      },
      { key: 'showPreferences', label: 'Show "Manage Preferences" button', type: 'toggle' },
      { key: 'preferencesLabel', label: 'Preferences button label', type: 'text', placeholder: 'Manage Preferences', condition: p => Boolean(p.showPreferences) },
      { key: 'policyLabel', label: 'Privacy policy link label', type: 'text' },
      { key: 'policyUrl', label: 'Privacy policy URL', type: 'url' },
      { key: 'bgColor', label: 'Background colour', type: 'color' },
      { key: 'textColor', label: 'Text colour', type: 'color' },
      { key: 'btnColor', label: 'Button colour', type: 'color' },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      text: 'We use cookies to improve your experience and analyze site traffic.',
      acceptLabel: 'Accept All',
      declineLabel: 'Decline Essential Only',
      targeting: 'gdpr-only',
      showPreferences: true,
      preferencesLabel: 'Manage Preferences',
      policyLabel: 'Privacy Policy',
      policyUrl: '/privacy',
      bgColor: '#0f172a',
      textColor: '#ffffff',
      btnColor: '#00dc82',
      padding: { top: 16, right: 24, bottom: 16, left: 24, unit: 'px' },
    },
  },

  // ── Footer ────────────────────────────────────────────────────────────────
  {
    id: 'canvas-footer',
    name: 'Footer',
    description: 'Standard site footer with links and branding',
    icon: 'i-lucide-panel-bottom',
    category: 'layout',
    component: 'CanvasBlockFooter',
    thumbnailColor: '#f8fafc',
    fields: [
      { key: 'logoText', label: 'Logo text', type: 'text' },
      { key: 'logoIcon', label: 'Logo icon class', type: 'text' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'col1Title', label: 'Column 1 Title', type: 'text' },
      { key: 'col1Links', label: 'Column 1 Links (JSON array)', type: 'text' },
      { key: 'col2Title', label: 'Column 2 Title', type: 'text' },
      { key: 'col2Links', label: 'Column 2 Links (JSON array)', type: 'text' },
      { key: 'copyrightText', label: 'Copyright text', type: 'text' },
      { key: 'bgColor', label: 'Background colour', type: 'color' },
      { key: 'textColor', label: 'Text colour', type: 'color' },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      logoText: 'My Site',
      logoIcon: 'i-lucide-globe',
      description: 'A beautiful website built on our custom block platform.',
      col1Title: 'Links',
      col1Links: '[{"label":"Home","url":"/"},{"label":"About","url":"/about"}]',
      col2Title: 'Support',
      col2Links: '[{"label":"Contact","url":"/contact"},{"label":"Privacy","url":"/privacy"}]',
      copyrightText: '© 2026 My Site. All rights reserved.',
      bgColor: '#0f172a',
      textColor: '#9ca3af',
      padding: { top: 48, right: 24, bottom: 24, left: 24, unit: 'px' },
    },
  },

  // ── Standalone Button ──────────────────────────────────────────────────────
  {
    id: 'canvas-button',
    name: 'Button',
    description: 'Standalone call-to-action button',
    icon: 'i-lucide-square-play',
    category: 'cta',
    component: 'CanvasBlockButton',
    thumbnailColor: '#ecfdf5',
    fields: [
      { key: 'label', label: 'Button Label', type: 'text', placeholder: 'Click here' },
      { key: 'url', label: 'Button URL', type: 'url', placeholder: '/' },
      {
        key: 'align',
        label: 'Alignment',
        type: 'select',
        options: [
          { label: 'Left', value: 'left' },
          { label: 'Center', value: 'center' },
          { label: 'Right', value: 'right' },
        ],
      },
      {
        key: 'size',
        label: 'Size',
        type: 'select',
        options: [
          { label: 'Small', value: 'sm' },
          { label: 'Medium', value: 'md' },
          { label: 'Large', value: 'lg' },
        ],
      },
      {
        key: 'rounded',
        label: 'Corner shape',
        type: 'select',
        options: [
          { label: 'Square', value: 'none' },
          { label: 'Rounded', value: 'md' },
          { label: 'Extra Rounded', value: 'lg' },
          { label: 'Pill / Capsule', value: 'full' },
        ],
      },
      { key: 'bgColor', label: 'Button background colour', type: 'color' },
      { key: 'textColor', label: 'Button text colour', type: 'color' },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      label: 'Click here',
      url: '#',
      align: 'center',
      size: 'md',
      rounded: 'lg',
      bgColor: '#00dc82',
      textColor: '#0f172a',
      padding: { top: 16, right: 24, bottom: 16, left: 24, unit: 'px' },
    },
  },

  // ── Accordion / FAQ ────────────────────────────────────────────────────────
  {
    id: 'canvas-accordion',
    name: 'Accordion',
    description: 'Collapsible FAQ panels',
    icon: 'i-lucide-fold-vertical',
    category: 'content',
    component: 'CanvasBlockAccordion',
    thumbnailColor: '#f5f3ff',
    fields: [
      { key: 'title', label: 'Section Title', type: 'text', placeholder: 'Frequently Asked Questions' },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Supporting text…' },
      { key: 'itemsJson', label: 'Items (JSON array of {question, answer})', type: 'text' },
      { key: 'bgColor', label: 'Background colour', type: 'color' },
      { key: 'textColor', label: 'Text colour', type: 'color' },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      title: 'Frequently Asked Questions',
      description: 'Everything you need to know about our product.',
      itemsJson: '[{"question":"How does NuxFlow work?","answer":"NuxFlow operates natively on Cloudflare Workers edge nodes. It fetches your content directly from D1/Turso and renders pages with Vue 3 server-side rendering."},{"question":"Do I need server configuration?","answer":"No, NuxFlow is fully serverless. You deploy it once to Cloudflare and it scales automatically with zero maintenance."}]',
      padding: { top: 48, right: 24, bottom: 48, left: 24, unit: 'px' },
    },
  },

  // ── Pricing Table ──────────────────────────────────────────────────────────
  {
    id: 'canvas-pricing',
    name: 'Pricing Table',
    description: 'Compare packages and plans side-by-side',
    icon: 'i-lucide-credit-card',
    category: 'cta',
    component: 'CanvasBlockPricing',
    thumbnailColor: '#fffbeb',
    fields: [
      { key: 'title', label: 'Section Title', type: 'text', placeholder: 'Simple, transparent pricing' },
      { key: 'description', label: 'Description', type: 'textarea', placeholder: 'Choose the plan that is right for you.' },
      {
        key: 'numPlans',
        label: 'Number of plans',
        type: 'select',
        options: [
          { label: '2 plans', value: '2' },
          { label: '3 plans', value: '3' },
        ],
      },
      // Plan 1
      { key: 'plan1Name', label: 'Plan 1 — Name', type: 'text', placeholder: 'Hobby' },
      { key: 'plan1Price', label: 'Plan 1 — Price', type: 'text', placeholder: '0' },
      { key: 'plan1Period', label: 'Plan 1 — Period', type: 'text', placeholder: '/mo' },
      { key: 'plan1Features', label: 'Plan 1 — Features (JSON array of strings)', type: 'text' },
      { key: 'plan1BtnLabel', label: 'Plan 1 — Button Label', type: 'text', placeholder: 'Start free' },
      { key: 'plan1BtnUrl', label: 'Plan 1 — Button URL', type: 'text', placeholder: '#' },
      { key: 'plan1Popular', label: 'Plan 1 — Popular (highlighted)', type: 'toggle' },
      // Plan 2
      { key: 'plan2Name', label: 'Plan 2 — Name', type: 'text', placeholder: 'Pro' },
      { key: 'plan2Price', label: 'Plan 2 — Price', type: 'text', placeholder: '29' },
      { key: 'plan2Period', label: 'Plan 2 — Period', type: 'text', placeholder: '/mo' },
      { key: 'plan2Features', label: 'Plan 2 — Features (JSON array of strings)', type: 'text' },
      { key: 'plan2BtnLabel', label: 'Plan 2 — Button Label', type: 'text', placeholder: 'Get started' },
      { key: 'plan2BtnUrl', label: 'Plan 2 — Button URL', type: 'text', placeholder: '#' },
      { key: 'plan2Popular', label: 'Plan 2 — Popular (highlighted)', type: 'toggle' },
      // Plan 3
      { key: 'plan3Name', label: 'Plan 3 — Name', type: 'text', placeholder: 'Enterprise', condition: p => p.numPlans === '3' },
      { key: 'plan3Price', label: 'Plan 3 — Price', type: 'text', placeholder: '99', condition: p => p.numPlans === '3' },
      { key: 'plan3Period', label: 'Plan 3 — Period', type: 'text', placeholder: '/mo', condition: p => p.numPlans === '3' },
      { key: 'plan3Features', label: 'Plan 3 — Features (JSON array of strings)', type: 'text', condition: p => p.numPlans === '3' },
      { key: 'plan3BtnLabel', label: 'Plan 3 — Button Label', type: 'text', placeholder: 'Contact sales', condition: p => p.numPlans === '3' },
      { key: 'plan3BtnUrl', label: 'Plan 3 — Button URL', type: 'text', placeholder: '#', condition: p => p.numPlans === '3' },
      { key: 'plan3Popular', label: 'Plan 3 — Popular (highlighted)', type: 'toggle', condition: p => p.numPlans === '3' },
      // Styles
      { key: 'bgColor', label: 'Background colour', type: 'color' },
      { key: 'textColor', label: 'Text colour', type: 'color' },
      { key: 'padding', label: 'Padding', type: 'spacing' },
    ],
    defaultProps: {
      title: 'Simple, transparent pricing',
      description: 'Choose the plan that is right for you.',
      numPlans: '3',
      plan1Name: 'Hobby',
      plan1Price: '0',
      plan1Period: '/mo',
      plan1Features: '["1 site", "Basic analytics", "Community support"]',
      plan1BtnLabel: 'Start free',
      plan1BtnUrl: '#',
      plan1Popular: false,
      plan2Name: 'Pro',
      plan2Price: '29',
      plan2Period: '/mo',
      plan2Features: '["Unlimited sites", "Detailed metrics", "Priority email support", "Custom domains"]',
      plan2BtnLabel: 'Get started',
      plan2BtnUrl: '#',
      plan2Popular: true,
      plan3Name: 'Enterprise',
      plan3Price: '99',
      plan3Period: '/mo',
      plan3Features: '["Dedicated instance", "SLA guarantee", "24/7 phone support", "Custom contracts"]',
      plan3BtnLabel: 'Contact sales',
      plan3BtnUrl: '#',
      plan3Popular: false,
      padding: { top: 48, right: 24, bottom: 48, left: 24, unit: 'px' },
    },
  },
]

// External bundled plugins can register their own block definitions here so
// the Canvas settings panel renders their fields correctly.
const _pluginDefinitions: CanvasBlockDefinition[] = []

export function registerBlockDefinition(def: CanvasBlockDefinition): void {
  if (!_pluginDefinitions.find(d => d.id === def.id)) {
    _pluginDefinitions.push(def)
  }
}

export function getPluginBlockDefinitions(): CanvasBlockDefinition[] {
  return _pluginDefinitions
}

export function getBlockDefinition(id: string): CanvasBlockDefinition | undefined {
  return CANVAS_BLOCKS.find(b => b.id === id) ?? _pluginDefinitions.find(b => b.id === id)
}
